Feature/forms practice
majovanilla/forms pull request #1
Opened 2019-11-22 21:51 UTC by majovainilla

Request code review for the project: 

- [ ] Create forms using erb

- [ ] Includes new view and controller (/users/new)

- [ ]  Includes edit view and controller (/users/id/edit)

- [ ] Includes extra credit to show validation errors

Thanks for the review!

2019-11-23 14:00 UTC, Oghenebrume50 requested changes
### STATUS: Changes Required 

Hi, team good job on this one everything works, just a few things to do to complete this project, see my comment below 

- Create a partial and reuse in the new and edit file

Raphael Noriode

2019-11-23 14:00 UTC, Oghenebrume50 commented on app/controllers/users_controller.rb
> +    # @user = User.new(username: params[:username], email: params[:email], password: params[:password])
Please delete commented codes

2019-11-23 14:00 UTC, Oghenebrume50 commented on app/views/users/new.html.erb
> +<% end %>
Use a regular HTML form and form_tag here then comment them out

2019-11-24 02:34 UTC, mosaaleb requested changes
## Hi @majovainilla, @fabricio-garcia :wave:

#### To get this project approved, we need to implement the new html form with three different approaches:

1. `html` forms. :x:
2. rails `form_tag` helper :x:
3. rails `form_for` :heavy_check_mark:

Let's add the first two approaches and comment them out.

- [x] **[OPTIONAL]** Please move out the css from the views. it's not readable to have css styles in your html. The right place is to put it under a `app/assets/stylesheets`.
**Also** there is no need to include the `html`, `head` or `body` tags in your views or partials. It's already in `application.html.erb`. All your partials files and views gets rendered around `<%= yield %>` in `application.html.erb`


#### Please handle the requirements and submit a new code review

##### Muhammad Ebeid

2019-11-24 02:34 UTC, mosaaleb commented on app/models/user.rb
> +  validates :email, presence: true
- [ ] **[OPTIONAL]** We can validate all attributes in one liner if they all share the same validator
`validates :username, :email, :password, presence: true`

2019-11-24 20:22 UTC, bolah2009 approved these changes
## Looks good to me :+1: 

Good job implementing the suggested changes.
### :heavy_check_mark: Approved

2019-11-24 20:29 UTC, merged